### ISSUE TITLE
Deprecated field type error when running elastic_mapping shell

### ISSUE THREAD

**Issue by bmudda** [lorenzo/audit-stash#33]
When running the shell `bin/cake elastic_mapping Users --use-templates`, I get the following error:
```
Exception: No handler for type [multi_field] declared on field [password] [reason: Failed to parse mapping [user]: No handler for type [multi_field] declared on field [password]] in [/my-cakephp-app/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php, line 181]
2018-09-07 03:24:56 Error: [Elastica\Exception\ResponseException] No handler for type [multi_field] declared on field [password] [reason: Failed to parse mapping [user]: No handler for type [multi_field] declared on field [password]] in /my-cakephp-app/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 181
Stack Trace:
#0 /my-cakephp-app/vendor/ruflin/elastica/lib/Elastica/Request.php(193): Elastica\Transport\Http->exec(Object(Elastica\Request), Array)
#1 /my-cakephp-app/vendor/ruflin/elastica/lib/Elastica/Client.php(688): Elastica\Request->send()
#2 [internal function]: Elastica\Client->request('_template/templ...', 'PUT', Array)
#3 /my-cakephp-app/vendor/cakephp/elastic-search/src/Datasource/Connection.php(92): call_user_func_array(Array, Array)
#4 /my-cakephp-app/vendor/lorenzo/audit-stash/src/Shell/ElasticMappingShell.php(109): Cake\ElasticSearch\Datasource\Connection->__call('request', Array)
#5 /my-cakephp-app/vendor/cakephp/cakephp/src/Console/Shell.php(532): AuditStash\Shell\ElasticMappingShell->main(Object(Cake\ORM\Table))
#6 /my-cakephp-app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(342): Cake\Console\Shell->runCommand(Array, true)
#7 /my-cakephp-app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(164): Cake\Console\CommandRunner->runShell(Object(AuditStash\Shell\ElasticMappingShell), Array)
#8 /my-cakephp-app/bin/cake.php(28): Cake\Console\CommandRunner->run(Array)
#9 {main}
```
I have attached [user-mapping.txt](https://github.com/lorenzo/audit-stash/files/2359390/user-mapping.txt) that contains the json mapping that is generated by the `--dry-run` option.

I am using `lorenzo/audit-stash:2.0.2` and `cakephp/elastic-search:2.0.0-RC2`

**Comment by lorenzo** [comment]
Would you like to fix this?

**Comment by bmudda** [comment]
@lorenzo Created a pull request https://github.com/lorenzo/audit-stash/pull/34
